# Generated by Django 5.0.3 on 2024-03-18 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesto', '0002_task_due_date_task_is_complete_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 4, 52, 52, 818770)),
        ),
    ]
